---

- name: Start privatebin docker
  community.docker.docker_compose:
      project_src: /home/docker/
      files: privatebin.yaml
      project_name: privatebin
  async: 120
  poll: 10
  when: not ansible_check_mode
